import { Geist, Geist_Mono } from 'next/font/google';
import Footer from './component/Footer';
import Header from './component/Header';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Swell | Next.js Demo',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Header />
                <div className="hero bg-base-200 min-h-screen">
                    <div className="hero-content flex-col">{children}</div>
                </div>
                <Footer />
            </body>
        </html>
    );
}
